# Source: https://github.com/blake/external-mdns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-mdns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-mdns
  template:
    metadata:
      labels:
        app: external-mdns
    spec:
      hostNetwork: true
      containers:
      - name: external-mdns
        image: blakec/external-mdns:latest
        args:
        - -source=ingress
        - -source=service
